macos_min_version:             # [osx and x86_64]
  - 10.13                      # [osx and x86_64]
MACOSX_DEPLOYMENT_TARGET:      # [osx and x86_64]
  - 10.13                      # [osx and x86_64]

ogre:
  - 1.10
  - 1.12

c_compiler:  # [win]
- vs2019  # [win]
cxx_compiler:  # [win]
- vs2019  # [win]
